/**
 * AUTO-GENERATED by scripts/sync-drive-manifest.ts — do not edit by hand.
 * Run: npm run drive:sync-manifests
 */
export type DriveMediaEntry = {
  index: number
  driveFileId: string
  name: string
  mimeType: string
  modifiedTime: string
}

export type DriveUnmappedEntry = {
  name: string
  reason: string
}

export type BatchDriveManifest = {
  batchId: string
  syncedAt: string
  clips: DriveMediaEntry[]
  videos: DriveMediaEntry[]
  thumbnails: DriveMediaEntry[]
  unmapped: DriveUnmappedEntry[]
}

export const DRIVE_MANIFESTS: Record<string, BatchDriveManifest> = {
  "b-204": {
    "batchId": "b-204",
    "syncedAt": "2026-05-15T16:49:06.328Z",
    "clips": [
      {
        "index": 1,
        "driveFileId": "1oaEGyaO92WzZgOpAVwwBEcRi9Zhe0qT-",
        "name": "1.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-11T18:05:12.000Z"
      },
      {
        "index": 2,
        "driveFileId": "15jjN3jp_oLU1M6CQoFBUjcqoOhd5yBGM",
        "name": "2.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-11T18:09:46.000Z"
      },
      {
        "index": 3,
        "driveFileId": "1dJvQQwmaV_XO6YJEUV2wCaNOaBaMdeeJ",
        "name": "3.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-11T18:17:14.000Z"
      },
      {
        "index": 4,
        "driveFileId": "1iF0Y4rYeQjZ3SwOCyK2HA5y8MQqVKwm5",
        "name": "4.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-11T18:19:52.000Z"
      },
      {
        "index": 5,
        "driveFileId": "10b_58mvYRL7RGbtuOoVsEpC1_Ty1oYKa",
        "name": "5.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-11T18:27:22.000Z"
      },
      {
        "index": 6,
        "driveFileId": "1UwktAZcLKtYRoDNB1CqXcdZlIuF1iwRI",
        "name": "6.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-11T18:30:05.000Z"
      },
      {
        "index": 7,
        "driveFileId": "1MCKi_9231Egw66U3b2rGutZETCgPtB-t",
        "name": "7.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-11T18:34:40.000Z"
      },
      {
        "index": 8,
        "driveFileId": "1clRAr2IyFlEZUHxxQGWM6nojprq0LjGT",
        "name": "8.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-12T18:34:43.000Z"
      },
      {
        "index": 9,
        "driveFileId": "1WrQwbcjxeZ4OfGTitJX-wUSERM_lu0ou",
        "name": "9.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-12T18:36:43.000Z"
      },
      {
        "index": 10,
        "driveFileId": "13vEAvIlkL-8yQEo1Rcf2MGS7hlrtGbT4",
        "name": "10.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-12T18:38:21.000Z"
      },
      {
        "index": 11,
        "driveFileId": "1YKDdAi7O7ktAxDPX77OttOQDkT6PMPts",
        "name": "11.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-12T18:39:31.000Z"
      },
      {
        "index": 12,
        "driveFileId": "1XqRliY_p4hrh_HkV7vCN4wegEwRQcD1V",
        "name": "12.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-12T18:40:59.000Z"
      },
      {
        "index": 13,
        "driveFileId": "1TnBw2Uw6-x4uAX1tQrrXknYDLoq5vmJ8",
        "name": "13.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-12T18:42:18.000Z"
      },
      {
        "index": 14,
        "driveFileId": "1gMUxBgupVj0X9dqptvALNX1f0wXVP245",
        "name": "14.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-13T18:42:46.000Z"
      },
      {
        "index": 15,
        "driveFileId": "19AUF9PsBlaMajXMkZ1Hh5ljSi8hsjOI3",
        "name": "15.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-13T18:47:26.000Z"
      },
      {
        "index": 16,
        "driveFileId": "1NgIPeoaeltDlgrXzM-sJ1SEJ-HY2QMmE",
        "name": "16.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-13T18:58:23.000Z"
      },
      {
        "index": 17,
        "driveFileId": "1OQJhUVsYacjdAL9GfcIaQEc7-sKGR5AS",
        "name": "17.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-13T19:02:34.000Z"
      },
      {
        "index": 18,
        "driveFileId": "1QMeC_-iExI3YmHQhue97BL-CUkKwwKHS",
        "name": "18.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-13T19:10:26.000Z"
      },
      {
        "index": 19,
        "driveFileId": "1Xg2F_1omRLlCqZALADb_1DqI6iCxqPkB",
        "name": "19.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-13T19:16:57.000Z"
      },
      {
        "index": 20,
        "driveFileId": "1DanED6MWVvkwZKTvtYDFDaHGMOh6dyrr",
        "name": "20.mov",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-05-13T19:18:52.000Z"
      }
    ],
    "videos": [
      {
        "index": 1,
        "driveFileId": "1urDEwYEbcfZhM6VP2_E-WFxwmmaTLIxU",
        "name": "1",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T18:42:39.148Z"
      },
      {
        "index": 2,
        "driveFileId": "1pansN3k_T5pe8vH2PKZkFjiOCfY5TpOW",
        "name": "2",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T19:08:10.408Z"
      },
      {
        "index": 3,
        "driveFileId": "1U9CYMaEJOu09TGAMh29IAvZhcdv8Vkb6",
        "name": "3",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T19:21:52.969Z"
      },
      {
        "index": 4,
        "driveFileId": "1EOCki1gzHKKRxGch-DusX0h_GYgwakgC",
        "name": "4",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-27T17:31:46.147Z"
      },
      {
        "index": 5,
        "driveFileId": "1fgdRAyYhS059KmrkEetJymq01eSmPN3m",
        "name": "5",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T19:35:07.315Z"
      },
      {
        "index": 6,
        "driveFileId": "1WPgc58UjpvK2LbSycWywYQ8CtkkX5UL-",
        "name": "6",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T19:46:48.413Z"
      },
      {
        "index": 7,
        "driveFileId": "1a8-yllQkOzX4_8hstCvrsUpPOgnVNpxZ",
        "name": "7",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-27T18:15:00.471Z"
      },
      {
        "index": 8,
        "driveFileId": "1BjGEpf1jVb7aUL3qCW9TU2qPDuB6rYKQ",
        "name": "8",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T20:03:19.402Z"
      },
      {
        "index": 9,
        "driveFileId": "1BEAarOoTQLFudRzrX69oEDOGmjtVXb-D",
        "name": "9",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T20:15:48.908Z"
      },
      {
        "index": 10,
        "driveFileId": "1wAT3ouorsQf1Jym-1UBPKicHLgTCD2--",
        "name": "10",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T20:33:37.823Z"
      },
      {
        "index": 11,
        "driveFileId": "1dmNhVydybJP7tih_XiZND4FhxFFUqGLz",
        "name": "11",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T20:43:01.767Z"
      },
      {
        "index": 12,
        "driveFileId": "1_aG9CwguVA1YQLgRHt9DdvAR8C-Dr-7m",
        "name": "12",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T20:50:04.033Z"
      },
      {
        "index": 13,
        "driveFileId": "1-asZYLePNnF7HNabTBGL0f2c2LKH50fc",
        "name": "13",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T20:56:50.232Z"
      },
      {
        "index": 14,
        "driveFileId": "1tdou4sGPMWomcYILZEC9nokoDtXxOn5r",
        "name": "14",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-28T08:28:12.761Z"
      },
      {
        "index": 15,
        "driveFileId": "1pQbuTzBLu08wU9e75TttiBdIEVALlGhl",
        "name": "15",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-30T21:04:33.246Z"
      },
      {
        "index": 16,
        "driveFileId": "1a6f8dP97YmlncAHxXSpxkCpgYMAzaOlC",
        "name": "16",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-27T20:37:41.184Z"
      },
      {
        "index": 17,
        "driveFileId": "1176-qKY8i-0TdEEsbiHOegPGDx9QrvzP",
        "name": "17",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-27T21:01:21.931Z"
      },
      {
        "index": 18,
        "driveFileId": "1cwjbUgyBGbh-DVItOkSeaudpNoFsf3Q5",
        "name": "18",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-28T08:29:57.794Z"
      },
      {
        "index": 19,
        "driveFileId": "1KgqW9YRlZ2iZ-2-NE_JJT1AWzsGduJVM",
        "name": "19",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-27T21:31:07.179Z"
      },
      {
        "index": 20,
        "driveFileId": "166cD3nQcmOqXzj-WlBNl6_-F4t-a80lx",
        "name": "20",
        "mimeType": "video/quicktime",
        "modifiedTime": "2026-04-28T08:44:02.999Z"
      }
    ],
    "thumbnails": [
      {
        "index": 1,
        "driveFileId": "1WwD32P5iSG1q2S5lZRH9YpP6VAIzmBMy",
        "name": "1",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:06:36.820Z"
      },
      {
        "index": 2,
        "driveFileId": "1MjVP4JT4CxbU6s-FvX86Jw0-t5AIH7b4",
        "name": "2",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:06:54.261Z"
      },
      {
        "index": 3,
        "driveFileId": "1fPHNIC7TXt0_BhUiN-rtCoFYWQvDgqmE",
        "name": "3",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:09:02.109Z"
      },
      {
        "index": 4,
        "driveFileId": "1UmfWabKMljnbtI-MKDc7kgnj6wWYscLE",
        "name": "4",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-27T17:31:52.736Z"
      },
      {
        "index": 5,
        "driveFileId": "1_2VUCNOxejNRXGuXahJnC7-_sFf7hOhS",
        "name": "5",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:09:17.583Z"
      },
      {
        "index": 6,
        "driveFileId": "1xfBNMSciW2cIhY8-pMuWUTD6TOoojcU8",
        "name": "6",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:09:28.450Z"
      },
      {
        "index": 7,
        "driveFileId": "1vH4R4yzLQUAKvc1jRONsr2NkRJBqImoQ",
        "name": "7",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-27T18:14:35.521Z"
      },
      {
        "index": 8,
        "driveFileId": "1Jh-8qqT1fcNXyxITfm48Ph5anw9v1SDG",
        "name": "8",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:11:23.930Z"
      },
      {
        "index": 9,
        "driveFileId": "134kQoqxDI_EVbpyjasNru-XDZ9SbDY0L",
        "name": "9",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:11:34.959Z"
      },
      {
        "index": 10,
        "driveFileId": "14jqk9B84dhRCxs_xISsPW_z23qbG_37j",
        "name": "10",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:13:13.953Z"
      },
      {
        "index": 11,
        "driveFileId": "1CqETgNWi6LTe2aGmVzbCjXFW_ZadKGck",
        "name": "11",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:13:34.388Z"
      },
      {
        "index": 12,
        "driveFileId": "1MLzVxIdKuNV2XN4hSjlll_ZpQWlW5Rxn",
        "name": "12",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T20:50:53.136Z"
      },
      {
        "index": 13,
        "driveFileId": "1hRH8SmRrVU9acUxqttXS2VTfWLlm-XbU",
        "name": "13",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T20:57:05.006Z"
      },
      {
        "index": 14,
        "driveFileId": "1D_XbhtmKxVh7LuJFzRi44J1P0kIxi_bV",
        "name": "14",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-27T20:14:23.465Z"
      },
      {
        "index": 15,
        "driveFileId": "1U6hmQ8earWo88os3POpZX3YEl100F_jM",
        "name": "15",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-30T21:04:53.705Z"
      },
      {
        "index": 16,
        "driveFileId": "1_5pjPun4T5BuVdC64Yj3J1sAfBXlhyZy",
        "name": "16",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-05-01T08:04:13.301Z"
      },
      {
        "index": 17,
        "driveFileId": "19GN3Mkc2-5F0mFmjKLOvcXVvp8o2yUrv",
        "name": "17",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-27T21:00:46.425Z"
      },
      {
        "index": 18,
        "driveFileId": "1y2cLIP03SNH00vI-GKXNyI3YoXAsfRtV",
        "name": "18",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-27T21:19:53.389Z"
      },
      {
        "index": 19,
        "driveFileId": "1sRBPWvurbPN0B0gR1byMy3oFKxJPRLp5",
        "name": "19",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-27T21:30:38.020Z"
      },
      {
        "index": 20,
        "driveFileId": "1gbEwKkKhLZO7j6lid2_5X4Cq6M41wfNG",
        "name": "20",
        "mimeType": "image/jpeg",
        "modifiedTime": "2026-04-27T21:38:56.015Z"
      }
    ],
    "unmapped": []
  }
}
