export {
  MOCK_USERS,
  type EmployeeKind,
  type MockUserRecord,
  type UserRole,
} from './users'
export {
  getClientClipReview,
  getClientFinalReview,
  getClientIdeaReview,
  getClientTextReview,
  SAMPLE_VIDEO_SRC,
  type ClientClipCandidate,
  type ClientClipReviewDetail,
  type ClipRecommendation,
  type ClientFinalReviewDetail,
  type ClientIdeaReviewDetail,
  type ClientTextReviewDetail,
} from './clientCardDetails'
export {
  MOCK_CLIENT_CLIP_BATCH_INDEX,
  MOCK_CLIENT_DASHBOARD,
  MOCK_CLIENT_FINAL_REVIEW_INDEX,
  MOCK_CLIENT_IDEA_BATCH_INDEX,
  MOCK_CLIENT_TEXT_BATCH_INDEX,
  MOCK_CLIP_BATCHES,
  MOCK_FINAL_REVIEWS,
  MOCK_IDEA_BATCHES,
  MOCK_TEXT_BATCHES,
  type ClientAttentionKind,
  type ClientBatchRow,
  type ClientDashboardMock,
  type ClipBatchDetail,
  type FinalReviewListRow,
  type FinalReviewMock,
  type IdeaBatchDetail,
  type ScheduledVideoRow,
  type TextBatchDetail,
} from './clientDashboard'
export {
  MOCK_ADMIN_CLIENTS,
  MOCK_ADMIN_DEADLINE_TASKS,
  MOCK_ADMIN_PIPELINE_ITEMS,
  MOCK_ADMIN_PIPELINE_SUMMARY,
  type AdminClientAccount,
  type AdminDeadlineTask,
  type AdminPipelineItem,
  type AdminPipelineSummary,
  type InternalTaskAssignee,
  type PipelineOwnerKind,
} from './adminDashboard'
export {
  ADMIN_KANBAN_COLUMNS,
  MOCK_ADMIN_BATCH_FOLDERS,
  MOCK_ADMIN_CLIENT_PROFILES,
  MOCK_ADMIN_VIDEO_TICKETS,
  MOCK_STAFF_EDITORS,
  MOCK_STAFF_SMM,
  guidelinesSourceLabel,
  type AdminBatchFolder,
  type AdminBatchFolderStatus,
  type BatchScheduleRecord,
  type VideoQaTimestampFlag,
  type BatchClipReviewPhase,
  type BatchFootageFile,
  type BatchIntakePath,
  type AdminClientAccountStatus,
  type AdminClientProfile,
  type AdminVideoTicket,
  type BrandGuidelinesSource,
  type EditorWorkflowPhase,
  type StaffMember,
  type VideoPipelineOwner,
} from './adminWorkspace'
export {
  getMockEditorDashboard,
  listEditorTaskSummaries,
  MOCK_EDITOR_TASKS,
  type EditorDashboardMock,
  type EditorQaFlag,
  type EditorTaskDetail,
  type EditorTaskKind,
  type EditorTaskStatus,
  type EditorTaskSummary,
} from './editorDashboard'
export {
  MOCK_SMM_CLIP_BATCH_INDEX,
  MOCK_SMM_CLIP_BATCHES,
  MOCK_SMM_DASHBOARD,
  MOCK_SMM_IDEA_BATCH_INDEX,
  MOCK_SMM_IDEA_BATCHES,
  MOCK_SMM_QA_INDEX,
  MOCK_SMM_QA_TASKS,
  MOCK_SMM_SCHEDULE_DETAILS,
  MOCK_SMM_SCHEDULE_INDEX,
  MOCK_SMM_TEXT_BATCH_INDEX,
  MOCK_SMM_TEXT_BATCHES,
  type SmmAttentionKind,
  type SmmBatchRow,
  type SmmClipBatchDetail,
  type SmmClipBatchListRow,
  type SmmDashboardMock,
  type SmmIdeaBatchDetail,
  type SmmIdeaBatchListRow,
  type SmmQaDetail,
  type SmmQaFlagDraft,
  type SmmQaListRow,
  type SmmScheduleDetail,
  type SmmScheduleListRow,
  type SmmTextBatchDetail,
  type SmmTextBatchListRow,
} from './smmDashboard'
